# Header
menu:
  Home: /
  About: /about
rss: /atom.xml

feed:
  type: atom
  path: atom.xml
  limit: 20

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud



# Miscellaneous
google_analytics: 
favicon: /favicon.png
twitter: dnosker 
google_plus:
fb_admins:
fb_app_id:
